name: MPI Project CI/CD

on:
  push:
    branches: 
      - main
      - master
    paths:
      - '**.c'
      - '**.h'
      - 'CMakeLists.txt'
      - '.github/workflows/**'
  pull_request:
    branches: 
      - main
      - master
    paths:
      - '**.c'
      - '**.h'
      - 'CMakeLists.txt'
      - '.github/workflows/**'
  workflow_dispatch:  # Optional manual trigger

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Use GitHub-hosted Ubuntu runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up MPI
      run: |
        sudo apt-get update
        sudo apt-get install -y openmpi-bin openmpi-common libopenmpi-dev
        
    - name: Set up GCC
      run: |
        sudo apt-get install -y gcc g++ make cmake
        
    - name: Clean Build Directory
      run: |
        rm -rf build
        mkdir -p build
        
    - name: Configure CMake
      run: |
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        
    - name: Build
      run: |
        cd build
        make
        
    - name: Run Sequential Tests
      run: |
        cd build
        echo "Running sequential tests..."
        mpirun -np 1 --oversubscribe ./test_all_pairwise || echo "Sequential tests completed with status $?"
        
    - name: Run Distributed Tests
      run: |
        cd build
        echo "Running distributed tests..."
        export OMPI_MCA_btl_vader_single_copy_mechanism=none
        mpirun -np 2 --oversubscribe --mca btl_vader_single_copy_mechanism none ./test_distributed || echo "Distributed tests completed with status $?"
        
    - name: Run Performance Tests
      run: |
        cd build
        echo "Running performance tests..."
        export OMPI_MCA_btl_vader_single_copy_mechanism=none
        
        echo "Running sequential test with M=5, N=4, float"
        mpirun -np 1 --oversubscribe ./all_pairwise 5 4 float || echo "Test completed with status $?"
        
        echo "Running parallel test with M=5, N=4, float"
        mpirun -np 2 --oversubscribe --mca btl_vader_single_copy_mechanism none ./all_pairwise 5 4 float || echo "Test completed with status $?"
        
        echo "Running sequential test with M=10, N=8, double"
        mpirun -np 1 --oversubscribe ./all_pairwise 10 8 double || echo "Test completed with status $?"
        
        echo "Running parallel test with M=10, N=8, double"
        mpirun -np 2 --oversubscribe --mca btl_vader_single_copy_mechanism none ./all_pairwise 10 8 double || echo "Test completed with status $?"
        
        echo "Running sequential test with M=100, N=50, float"
        mpirun -np 1 --oversubscribe ./all_pairwise 100 50 float || echo "Test completed with status $?"
        
        echo "Running parallel test with M=100, N=50, float"
        mpirun -np 2 --oversubscribe --mca btl_vader_single_copy_mechanism none ./all_pairwise 100 50 float || echo "Test completed with status $?"
        
    - name: Create Test Results Directory
      run: |
        mkdir -p build/test_results
        touch build/test_results/test_results.txt
        touch build/test_results/performance_results.txt
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/test_results/
        if-no-files-found: warn
        
    - name: Run Memory Check
      run: |
        cd build
        valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt mpirun -np 1 --oversubscribe ./all_pairwise 5 4 float || echo "Memory check completed with status $?"
        
    - name: Upload Memory Check Results
      uses: actions/upload-artifact@v4
      with:
        name: memory-check-results
        path: build/valgrind-out.txt
        if-no-files-found: warn 